import 'dart:convert';

import 'package:weather_app/core/data/models/weather_info_response.dart';

WeatherInfoResponse mockedCurrentWeatherResponseForLisbon = WeatherInfoResponse.fromJson(jsonDecode('''
{
    "location": {
        "name": "Lisbon",
        "region": "Lisboa",
        "country": "Portugal",
        "lat": 38.72,
        "lon": -9.13,
        "tz_id": "Europe/Lisbon",
        "localtime_epoch": 1663584602,
        "localtime": "2022-09-19 11:50"
    },
    "current": {
        "last_updated_epoch": 1663584300,
        "last_updated": "2022-09-19 11:45",
        "temp_c": 26.0,
        "temp_f": 78.8,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 140,
        "wind_dir": "SE",
        "pressure_mb": 1014.0,
        "pressure_in": 29.94,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 65,
        "cloud": 25,
        "feelslike_c": 27.6,
        "feelslike_f": 81.6,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 6.0,
        "gust_mph": 10.5,
        "gust_kph": 16.9
    }
}
  '''));


WeatherInfoResponse mockedForecastWeatherResponseForLisbon = WeatherInfoResponse.fromJson(jsonDecode('''
{
    "location": {
        "name": "Olisipo",
        "region": "Lisboa",
        "country": "Portugal",
        "lat": 38.72,
        "lon": -9.13,
        "tz_id": "Europe/Lisbon",
        "localtime_epoch": 1663584775,
        "localtime": "2022-09-19 11:52"
    },
    "current": {
        "last_updated_epoch": 1663584300,
        "last_updated": "2022-09-19 11:45",
        "temp_c": 26.0,
        "temp_f": 78.8,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 140,
        "wind_dir": "SE",
        "pressure_mb": 1015.0,
        "pressure_in": 29.97,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 65,
        "cloud": 25,
        "feelslike_c": 27.5,
        "feelslike_f": 81.4,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 6.0,
        "gust_mph": 8.7,
        "gust_kph": 14.0
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2022-09-19",
                "date_epoch": 1663545600,
                "day": {
                    "maxtemp_c": 28.7,
                    "maxtemp_f": 83.7,
                    "mintemp_c": 21.4,
                    "mintemp_f": 70.5,
                    "avgtemp_c": 24.1,
                    "avgtemp_f": 75.4,
                    "maxwind_mph": 8.7,
                    "maxwind_kph": 14.0,
                    "totalprecip_mm": 1.7,
                    "totalprecip_in": 0.07,
                    "avgvis_km": 9.7,
                    "avgvis_miles": 6.0,
                    "avghumidity": 67.0,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 86,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "uv": 5.0
                },
                "astro": {
                    "sunrise": "07:22 AM",
                    "sunset": "07:39 PM",
                    "moonrise": "12:42 AM",
                    "moonset": "04:28 PM",
                    "moon_phase": "Last Quarter",
                    "moon_illumination": "30"
                },
                "hour": [
                    {
                        "time_epoch": 1663542000,
                        "time": "2022-09-19 00:00",
                        "temp_c": 22.1,
                        "temp_f": 71.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/386.png",
                            "code": 1273
                        },
                        "wind_mph": 2.0,
                        "wind_kph": 3.2,
                        "wind_degree": 347,
                        "wind_dir": "NNW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 1.1,
                        "precip_in": 0.04,
                        "humidity": 71,
                        "cloud": 81,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 22.1,
                        "windchill_f": 71.8,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 16.5,
                        "dewpoint_f": 61.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.8,
                        "gust_kph": 6.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663545600,
                        "time": "2022-09-19 01:00",
                        "temp_c": 21.9,
                        "temp_f": 71.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 346,
                        "wind_dir": "NNW",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 10,
                        "feelslike_c": 21.9,
                        "feelslike_f": 71.4,
                        "windchill_c": 21.9,
                        "windchill_f": 71.4,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 16.3,
                        "dewpoint_f": 61.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663549200,
                        "time": "2022-09-19 02:00",
                        "temp_c": 21.8,
                        "temp_f": 71.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 22,
                        "wind_dir": "NNE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 11,
                        "feelslike_c": 21.8,
                        "feelslike_f": 71.2,
                        "windchill_c": 21.8,
                        "windchill_f": 71.2,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 16.0,
                        "dewpoint_f": 60.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.1,
                        "gust_kph": 8.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663552800,
                        "time": "2022-09-19 03:00",
                        "temp_c": 21.7,
                        "temp_f": 71.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 80,
                        "wind_dir": "E",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 80,
                        "feelslike_c": 21.7,
                        "feelslike_f": 71.1,
                        "windchill_c": 21.7,
                        "windchill_f": 71.1,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 15.9,
                        "dewpoint_f": 60.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 86,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.1,
                        "gust_kph": 8.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663556400,
                        "time": "2022-09-19 04:00",
                        "temp_c": 21.5,
                        "temp_f": 70.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 120,
                        "wind_dir": "ESE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 12,
                        "feelslike_c": 21.5,
                        "feelslike_f": 70.7,
                        "windchill_c": 21.5,
                        "windchill_f": 70.7,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 15.9,
                        "dewpoint_f": 60.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663560000,
                        "time": "2022-09-19 05:00",
                        "temp_c": 21.5,
                        "temp_f": 70.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 143,
                        "wind_dir": "SE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 13,
                        "feelslike_c": 21.5,
                        "feelslike_f": 70.7,
                        "windchill_c": 21.5,
                        "windchill_f": 70.7,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 15.8,
                        "dewpoint_f": 60.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663563600,
                        "time": "2022-09-19 06:00",
                        "temp_c": 21.4,
                        "temp_f": 70.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 107,
                        "wind_dir": "ESE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 71,
                        "cloud": 14,
                        "feelslike_c": 21.4,
                        "feelslike_f": 70.5,
                        "windchill_c": 21.4,
                        "windchill_f": 70.5,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 15.9,
                        "dewpoint_f": 60.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663567200,
                        "time": "2022-09-19 07:00",
                        "temp_c": 21.5,
                        "temp_f": 70.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 80,
                        "wind_dir": "E",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 72,
                        "cloud": 89,
                        "feelslike_c": 21.5,
                        "feelslike_f": 70.7,
                        "windchill_c": 21.5,
                        "windchill_f": 70.7,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 16.2,
                        "dewpoint_f": 61.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 80,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663570800,
                        "time": "2022-09-19 08:00",
                        "temp_c": 22.3,
                        "temp_f": 72.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 80,
                        "wind_dir": "E",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 21,
                        "feelslike_c": 24.7,
                        "feelslike_f": 76.5,
                        "windchill_c": 22.3,
                        "windchill_f": 72.1,
                        "heatindex_c": 24.7,
                        "heatindex_f": 76.5,
                        "dewpoint_c": 16.6,
                        "dewpoint_f": 61.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663574400,
                        "time": "2022-09-19 09:00",
                        "temp_c": 23.3,
                        "temp_f": 73.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                            "code": 1273
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 115,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.95,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 69,
                        "cloud": 77,
                        "feelslike_c": 25.2,
                        "feelslike_f": 77.4,
                        "windchill_c": 23.3,
                        "windchill_f": 73.9,
                        "heatindex_c": 25.2,
                        "heatindex_f": 77.4,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 63.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663578000,
                        "time": "2022-09-19 10:00",
                        "temp_c": 24.5,
                        "temp_f": 76.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 131,
                        "wind_dir": "SE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 65,
                        "cloud": 14,
                        "feelslike_c": 26.0,
                        "feelslike_f": 78.8,
                        "windchill_c": 24.5,
                        "windchill_f": 76.1,
                        "heatindex_c": 26.0,
                        "heatindex_f": 78.8,
                        "dewpoint_c": 17.5,
                        "dewpoint_f": 63.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663581600,
                        "time": "2022-09-19 11:00",
                        "temp_c": 26.9,
                        "temp_f": 80.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 132,
                        "wind_dir": "SE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 61,
                        "cloud": 21,
                        "feelslike_c": 28.3,
                        "feelslike_f": 82.9,
                        "windchill_c": 26.9,
                        "windchill_f": 80.4,
                        "heatindex_c": 28.3,
                        "heatindex_f": 82.9,
                        "dewpoint_c": 18.7,
                        "dewpoint_f": 65.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.2,
                        "gust_kph": 11.5,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1663585200,
                        "time": "2022-09-19 12:00",
                        "temp_c": 27.9,
                        "temp_f": 82.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 130,
                        "wind_dir": "SE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.95,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 23,
                        "feelslike_c": 29.3,
                        "feelslike_f": 84.7,
                        "windchill_c": 27.9,
                        "windchill_f": 82.2,
                        "heatindex_c": 29.3,
                        "heatindex_f": 84.7,
                        "dewpoint_c": 18.7,
                        "dewpoint_f": 65.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1663588800,
                        "time": "2022-09-19 13:00",
                        "temp_c": 28.3,
                        "temp_f": 82.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 109,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 54,
                        "cloud": 51,
                        "feelslike_c": 29.5,
                        "feelslike_f": 85.1,
                        "windchill_c": 28.3,
                        "windchill_f": 82.9,
                        "heatindex_c": 29.5,
                        "heatindex_f": 85.1,
                        "dewpoint_c": 18.0,
                        "dewpoint_f": 64.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663592400,
                        "time": "2022-09-19 14:00",
                        "temp_c": 28.7,
                        "temp_f": 83.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 2.0,
                        "wind_kph": 3.2,
                        "wind_degree": 95,
                        "wind_dir": "E",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 52,
                        "cloud": 74,
                        "feelslike_c": 29.9,
                        "feelslike_f": 85.8,
                        "windchill_c": 28.7,
                        "windchill_f": 83.7,
                        "heatindex_c": 29.9,
                        "heatindex_f": 85.8,
                        "dewpoint_c": 17.9,
                        "dewpoint_f": 64.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 2.7,
                        "gust_kph": 4.3,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663596000,
                        "time": "2022-09-19 15:00",
                        "temp_c": 28.5,
                        "temp_f": 83.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 212,
                        "wind_dir": "SSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 55,
                        "cloud": 56,
                        "feelslike_c": 29.9,
                        "feelslike_f": 85.8,
                        "windchill_c": 28.5,
                        "windchill_f": 83.3,
                        "heatindex_c": 29.9,
                        "heatindex_f": 85.8,
                        "dewpoint_c": 18.5,
                        "dewpoint_f": 65.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 3.1,
                        "gust_kph": 5.0,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663599600,
                        "time": "2022-09-19 16:00",
                        "temp_c": 27.7,
                        "temp_f": 81.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 235,
                        "wind_dir": "SW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 45,
                        "feelslike_c": 29.0,
                        "feelslike_f": 84.2,
                        "windchill_c": 27.7,
                        "windchill_f": 81.9,
                        "heatindex_c": 29.0,
                        "heatindex_f": 84.2,
                        "dewpoint_c": 18.4,
                        "dewpoint_f": 65.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 10.1,
                        "gust_kph": 16.2,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663603200,
                        "time": "2022-09-19 17:00",
                        "temp_c": 26.0,
                        "temp_f": 78.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 242,
                        "wind_dir": "WSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 63,
                        "cloud": 46,
                        "feelslike_c": 27.4,
                        "feelslike_f": 81.3,
                        "windchill_c": 26.0,
                        "windchill_f": 78.8,
                        "heatindex_c": 27.4,
                        "heatindex_f": 81.3,
                        "dewpoint_c": 18.5,
                        "dewpoint_f": 65.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663606800,
                        "time": "2022-09-19 18:00",
                        "temp_c": 25.3,
                        "temp_f": 77.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 68,
                        "cloud": 52,
                        "feelslike_c": 26.8,
                        "feelslike_f": 80.2,
                        "windchill_c": 25.3,
                        "windchill_f": 77.5,
                        "heatindex_c": 26.8,
                        "heatindex_f": 80.2,
                        "dewpoint_c": 18.9,
                        "dewpoint_f": 66.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663610400,
                        "time": "2022-09-19 19:00",
                        "temp_c": 24.5,
                        "temp_f": 76.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Thundery outbreaks possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                            "code": 1087
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 249,
                        "wind_dir": "WSW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 79,
                        "feelslike_c": 26.1,
                        "feelslike_f": 79.0,
                        "windchill_c": 24.5,
                        "windchill_f": 76.1,
                        "heatindex_c": 26.1,
                        "heatindex_f": 79.0,
                        "dewpoint_c": 18.7,
                        "dewpoint_f": 65.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663614000,
                        "time": "2022-09-19 20:00",
                        "temp_c": 23.2,
                        "temp_f": 73.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 247,
                        "wind_dir": "WSW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 74,
                        "cloud": 24,
                        "feelslike_c": 25.1,
                        "feelslike_f": 77.2,
                        "windchill_c": 23.2,
                        "windchill_f": 73.8,
                        "heatindex_c": 25.1,
                        "heatindex_f": 77.2,
                        "dewpoint_c": 18.3,
                        "dewpoint_f": 64.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663617600,
                        "time": "2022-09-19 21:00",
                        "temp_c": 22.9,
                        "temp_f": 73.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/386.png",
                            "code": 1273
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 261,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 76,
                        "cloud": 76,
                        "feelslike_c": 25.0,
                        "feelslike_f": 77.0,
                        "windchill_c": 22.9,
                        "windchill_f": 73.2,
                        "heatindex_c": 25.0,
                        "heatindex_f": 77.0,
                        "dewpoint_c": 18.5,
                        "dewpoint_f": 65.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 63,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663621200,
                        "time": "2022-09-19 22:00",
                        "temp_c": 22.6,
                        "temp_f": 72.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 269,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 17,
                        "feelslike_c": 24.8,
                        "feelslike_f": 76.6,
                        "windchill_c": 22.6,
                        "windchill_f": 72.7,
                        "heatindex_c": 24.8,
                        "heatindex_f": 76.6,
                        "dewpoint_c": 18.4,
                        "dewpoint_f": 65.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663624800,
                        "time": "2022-09-19 23:00",
                        "temp_c": 22.4,
                        "temp_f": 72.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 278,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 17,
                        "feelslike_c": 24.7,
                        "feelslike_f": 76.5,
                        "windchill_c": 22.4,
                        "windchill_f": 72.3,
                        "heatindex_c": 24.7,
                        "heatindex_f": 76.5,
                        "dewpoint_c": 18.2,
                        "dewpoint_f": 64.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.9,
                        "gust_kph": 11.2,
                        "uv": 1.0
                    }
                ]
            },
            {
                "date": "2022-09-20",
                "date_epoch": 1663632000,
                "day": {
                    "maxtemp_c": 29.3,
                    "maxtemp_f": 84.7,
                    "mintemp_c": 21.1,
                    "mintemp_f": 70.0,
                    "avgtemp_c": 23.5,
                    "avgtemp_f": 74.3,
                    "maxwind_mph": 11.2,
                    "maxwind_kph": 18.0,
                    "totalprecip_mm": 10.2,
                    "totalprecip_in": 0.4,
                    "avgvis_km": 9.8,
                    "avgvis_miles": 6.0,
                    "avghumidity": 73.0,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 86,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Moderate rain",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                        "code": 1189
                    },
                    "uv": 5.0
                },
                "astro": {
                    "sunrise": "07:22 AM",
                    "sunset": "07:37 PM",
                    "moonrise": "01:37 AM",
                    "moonset": "05:11 PM",
                    "moon_phase": "Last Quarter",
                    "moon_illumination": "22"
                },
                "hour": [
                    {
                        "time_epoch": 1663628400,
                        "time": "2022-09-20 00:00",
                        "temp_c": 22.1,
                        "temp_f": 71.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 278,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 20,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 22.1,
                        "windchill_f": 71.8,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 18.0,
                        "dewpoint_f": 64.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663632000,
                        "time": "2022-09-20 01:00",
                        "temp_c": 21.9,
                        "temp_f": 71.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 266,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 19,
                        "feelslike_c": 21.9,
                        "feelslike_f": 71.4,
                        "windchill_c": 21.9,
                        "windchill_f": 71.4,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 17.9,
                        "dewpoint_f": 64.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663635600,
                        "time": "2022-09-20 02:00",
                        "temp_c": 21.8,
                        "temp_f": 71.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 265,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 16,
                        "feelslike_c": 21.8,
                        "feelslike_f": 71.2,
                        "windchill_c": 21.8,
                        "windchill_f": 71.2,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 17.9,
                        "dewpoint_f": 64.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663639200,
                        "time": "2022-09-20 03:00",
                        "temp_c": 21.6,
                        "temp_f": 70.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 261,
                        "wind_dir": "W",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 15,
                        "feelslike_c": 21.6,
                        "feelslike_f": 70.9,
                        "windchill_c": 21.6,
                        "windchill_f": 70.9,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.8,
                        "gust_kph": 6.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663642800,
                        "time": "2022-09-20 04:00",
                        "temp_c": 21.5,
                        "temp_f": 70.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 14,
                        "feelslike_c": 21.5,
                        "feelslike_f": 70.7,
                        "windchill_c": 21.5,
                        "windchill_f": 70.7,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.8,
                        "gust_kph": 6.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663646400,
                        "time": "2022-09-20 05:00",
                        "temp_c": 21.3,
                        "temp_f": 70.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 230,
                        "wind_dir": "SW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 80,
                        "cloud": 16,
                        "feelslike_c": 21.3,
                        "feelslike_f": 70.3,
                        "windchill_c": 21.3,
                        "windchill_f": 70.3,
                        "heatindex_c": 24.3,
                        "heatindex_f": 75.7,
                        "dewpoint_c": 17.7,
                        "dewpoint_f": 63.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.8,
                        "gust_kph": 6.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663650000,
                        "time": "2022-09-20 06:00",
                        "temp_c": 21.2,
                        "temp_f": 70.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 219,
                        "wind_dir": "SW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 81,
                        "cloud": 15,
                        "feelslike_c": 21.2,
                        "feelslike_f": 70.2,
                        "windchill_c": 21.2,
                        "windchill_f": 70.2,
                        "heatindex_c": 24.3,
                        "heatindex_f": 75.7,
                        "dewpoint_c": 17.7,
                        "dewpoint_f": 63.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663653600,
                        "time": "2022-09-20 07:00",
                        "temp_c": 21.3,
                        "temp_f": 70.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 1.8,
                        "wind_kph": 2.9,
                        "wind_degree": 236,
                        "wind_dir": "WSW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 80,
                        "cloud": 82,
                        "feelslike_c": 21.3,
                        "feelslike_f": 70.3,
                        "windchill_c": 21.3,
                        "windchill_f": 70.3,
                        "heatindex_c": 24.3,
                        "heatindex_f": 75.7,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 62,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.9,
                        "gust_kph": 4.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663657200,
                        "time": "2022-09-20 08:00",
                        "temp_c": 22.2,
                        "temp_f": 72.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 1.3,
                        "wind_kph": 2.2,
                        "wind_degree": 242,
                        "wind_dir": "WSW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 76,
                        "cloud": 80,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 22.2,
                        "windchill_f": 72.0,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 17.7,
                        "dewpoint_f": 63.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 72,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.0,
                        "gust_kph": 3.2,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663660800,
                        "time": "2022-09-20 09:00",
                        "temp_c": 23.3,
                        "temp_f": 73.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Moderate rain at times",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/299.png",
                            "code": 1186
                        },
                        "wind_mph": 1.3,
                        "wind_kph": 2.2,
                        "wind_degree": 282,
                        "wind_dir": "WNW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 0.6,
                        "precip_in": 0.02,
                        "humidity": 71,
                        "cloud": 74,
                        "feelslike_c": 25.2,
                        "feelslike_f": 77.4,
                        "windchill_c": 23.3,
                        "windchill_f": 73.9,
                        "heatindex_c": 25.2,
                        "heatindex_f": 77.4,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 61,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 1.8,
                        "gust_kph": 2.9,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663664400,
                        "time": "2022-09-20 10:00",
                        "temp_c": 24.1,
                        "temp_f": 75.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 1.3,
                        "wind_kph": 2.2,
                        "wind_degree": 274,
                        "wind_dir": "W",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 68,
                        "cloud": 74,
                        "feelslike_c": 25.7,
                        "feelslike_f": 78.3,
                        "windchill_c": 24.1,
                        "windchill_f": 75.4,
                        "heatindex_c": 25.7,
                        "heatindex_f": 78.3,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 86,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 1.8,
                        "gust_kph": 2.9,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663668000,
                        "time": "2022-09-20 11:00",
                        "temp_c": 24.9,
                        "temp_f": 76.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                            "code": 1273
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 239,
                        "wind_dir": "WSW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 0.3,
                        "precip_in": 0.01,
                        "humidity": 66,
                        "cloud": 73,
                        "feelslike_c": 26.4,
                        "feelslike_f": 79.5,
                        "windchill_c": 24.9,
                        "windchill_f": 76.8,
                        "heatindex_c": 26.4,
                        "heatindex_f": 79.5,
                        "dewpoint_c": 18.2,
                        "dewpoint_f": 64.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 73,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.4,
                        "gust_kph": 5.4,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663671600,
                        "time": "2022-09-20 12:00",
                        "temp_c": 26.4,
                        "temp_f": 79.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                            "code": 1273
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 267,
                        "wind_dir": "W",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 1.4,
                        "precip_in": 0.06,
                        "humidity": 64,
                        "cloud": 88,
                        "feelslike_c": 27.9,
                        "feelslike_f": 82.2,
                        "windchill_c": 26.4,
                        "windchill_f": 79.5,
                        "heatindex_c": 27.9,
                        "heatindex_f": 82.2,
                        "dewpoint_c": 19.0,
                        "dewpoint_f": 66.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 84,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.0,
                        "gust_kph": 6.5,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663675200,
                        "time": "2022-09-20 13:00",
                        "temp_c": 26.8,
                        "temp_f": 80.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 260,
                        "wind_dir": "W",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 62,
                        "cloud": 18,
                        "feelslike_c": 28.2,
                        "feelslike_f": 82.8,
                        "windchill_c": 26.8,
                        "windchill_f": 80.2,
                        "heatindex_c": 28.2,
                        "heatindex_f": 82.8,
                        "dewpoint_c": 18.8,
                        "dewpoint_f": 65.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1663678800,
                        "time": "2022-09-20 14:00",
                        "temp_c": 29.1,
                        "temp_f": 84.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 10,
                        "feelslike_c": 31.5,
                        "feelslike_f": 88.7,
                        "windchill_c": 29.1,
                        "windchill_f": 84.4,
                        "heatindex_c": 31.5,
                        "heatindex_f": 88.7,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.2,
                        "gust_kph": 11.5,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1663682400,
                        "time": "2022-09-20 15:00",
                        "temp_c": 29.3,
                        "temp_f": 84.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 264,
                        "wind_dir": "W",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 82,
                        "feelslike_c": 31.8,
                        "feelslike_f": 89.2,
                        "windchill_c": 29.3,
                        "windchill_f": 84.7,
                        "heatindex_c": 31.8,
                        "heatindex_f": 89.2,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 76,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663686000,
                        "time": "2022-09-20 16:00",
                        "temp_c": 25.8,
                        "temp_f": 78.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                            "code": 1273
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 279,
                        "wind_dir": "W",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 65,
                        "cloud": 87,
                        "feelslike_c": 27.2,
                        "feelslike_f": 81.0,
                        "windchill_c": 25.8,
                        "windchill_f": 78.4,
                        "heatindex_c": 27.2,
                        "heatindex_f": 81.0,
                        "dewpoint_c": 18.7,
                        "dewpoint_f": 65.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 66,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663689600,
                        "time": "2022-09-20 17:00",
                        "temp_c": 25.1,
                        "temp_f": 77.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                            "code": 1273
                        },
                        "wind_mph": 10.7,
                        "wind_kph": 17.3,
                        "wind_degree": 297,
                        "wind_dir": "WNW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.6,
                        "precip_in": 0.02,
                        "humidity": 68,
                        "cloud": 89,
                        "feelslike_c": 26.6,
                        "feelslike_f": 79.9,
                        "windchill_c": 25.1,
                        "windchill_f": 77.2,
                        "heatindex_c": 26.6,
                        "heatindex_f": 79.9,
                        "dewpoint_c": 18.9,
                        "dewpoint_f": 66.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 17.7,
                        "gust_kph": 28.4,
                        "uv": 6.0
                    },
                    {
                        "time_epoch": 1663693200,
                        "time": "2022-09-20 18:00",
                        "temp_c": 24.5,
                        "temp_f": 76.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Moderate or heavy rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/356.png",
                            "code": 1243
                        },
                        "wind_mph": 11.2,
                        "wind_kph": 18.0,
                        "wind_degree": 309,
                        "wind_dir": "NW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 3.0,
                        "precip_in": 0.12,
                        "humidity": 72,
                        "cloud": 70,
                        "feelslike_c": 26.2,
                        "feelslike_f": 79.2,
                        "windchill_c": 24.5,
                        "windchill_f": 76.1,
                        "heatindex_c": 26.2,
                        "heatindex_f": 79.2,
                        "dewpoint_c": 19.0,
                        "dewpoint_f": 66.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 71,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 18.3,
                        "gust_kph": 29.5,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663696800,
                        "time": "2022-09-20 19:00",
                        "temp_c": 23.3,
                        "temp_f": 73.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                            "code": 1273
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 311,
                        "wind_dir": "NW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 75,
                        "cloud": 83,
                        "feelslike_c": 25.2,
                        "feelslike_f": 77.4,
                        "windchill_c": 23.3,
                        "windchill_f": 73.9,
                        "heatindex_c": 25.2,
                        "heatindex_f": 77.4,
                        "dewpoint_c": 18.6,
                        "dewpoint_f": 65.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 60,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.0,
                        "gust_kph": 17.6,
                        "uv": 5.0
                    },
                    {
                        "time_epoch": 1663700400,
                        "time": "2022-09-20 20:00",
                        "temp_c": 22.1,
                        "temp_f": 71.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy light rain with thunder",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/386.png",
                            "code": 1273
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 309,
                        "wind_dir": "NW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.7,
                        "precip_in": 0.03,
                        "humidity": 78,
                        "cloud": 76,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 22.1,
                        "windchill_f": 71.8,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 18.2,
                        "dewpoint_f": 64.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 84,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663704000,
                        "time": "2022-09-20 21:00",
                        "temp_c": 22.1,
                        "temp_f": 71.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 315,
                        "wind_dir": "NW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 1.4,
                        "precip_in": 0.06,
                        "humidity": 78,
                        "cloud": 77,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 22.1,
                        "windchill_f": 71.8,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 18.0,
                        "dewpoint_f": 64.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 61,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663707600,
                        "time": "2022-09-20 22:00",
                        "temp_c": 21.8,
                        "temp_f": 71.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 331,
                        "wind_dir": "NNW",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 78,
                        "cloud": 72,
                        "feelslike_c": 21.8,
                        "feelslike_f": 71.2,
                        "windchill_c": 21.8,
                        "windchill_f": 71.2,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 17.9,
                        "dewpoint_f": 64.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 68,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1663711200,
                        "time": "2022-09-20 23:00",
                        "temp_c": 21.1,
                        "temp_f": 70.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 92,
                        "wind_dir": "E",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 0.5,
                        "precip_in": 0.02,
                        "humidity": 83,
                        "cloud": 78,
                        "feelslike_c": 21.1,
                        "feelslike_f": 70.0,
                        "windchill_c": 21.1,
                        "windchill_f": 70.0,
                        "heatindex_c": 24.2,
                        "heatindex_f": 75.6,
                        "dewpoint_c": 18.1,
                        "dewpoint_f": 64.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 68,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}
'''));

