name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <=3.0.0"

dependencies:
  bloc: ^8.1.0
  build_runner: ^2.2.1
  cached_network_image: ^3.2.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  pretty_dio_logger: ^1.2.0-beta-1
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  geolocator: ^9.0.1
  get_it: ^7.2.0
  mocktail: ^0.3.0

dev_dependencies:
  freezed: ^2.1.0+1
  flutter_test:
    sdk: flutter
  test:
  bloc_test: ^9.1.0
  json_serializable: ^6.3.2
  environment_config: ^3.1.0
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Roman.ttf
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 900